# Generated by Django 3.2.6 on 2021-12-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ownership_type_coolant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='esn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
