# Generated by Django 3.2.6 on 2021-12-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211212_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='amc_end',
            field=models.DateField(null=True),
        ),
    ]
