# Generated by Django 3.2.6 on 2021-12-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_ownership_amc_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='last_airfilter',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='last_battery',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='last_coolant',
            field=models.DateField(null=True),
        ),
    ]
