# Generated by Django 3.2.6 on 2021-12-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_ownership_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='amc_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='contact_person',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='esn',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='kva',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='last_b',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='mail_id',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='model',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='phone_num',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='visit',
            field=models.IntegerField(null=True),
        ),
    ]
