# Generated by Django 3.2.6 on 2021-12-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211212_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='amc_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='amc_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='esn',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='kva',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='last_b',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='model',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='visit',
            field=models.IntegerField(),
        ),
    ]
