# Generated by Django 3.2.6 on 2021-12-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211213_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='customer_response',
            field=models.BooleanField(default=False),
        ),
    ]
