# Generated by Django 3.2.6 on 2021-12-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ownership_customer_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='remark_amcdue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='reminder_count_amcdue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
